gluster/gluster-csi-driver

- README.md
- pkg/glusterfs/driver.go
> added CI build status to readme

- README.md
Signed-off-by: hchiramm <hchiramm@redhat.com>
> Expand readme with compile steps.

- Makefile
> keep make targets in order.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
This adds templates for github issues to help users and developers better describe and prioritize bugs and new features.
> Add issue templates for bugs and features

- pkg/glusterfs/controllerserver.go
> Improve error messages and formatting.

- examples/kubernetes/app.yaml
> Update app pod yaml.

- pkg/glusterfs/controllerserver.go
This PR functionize parsing request and fill data on subjected structs. 
> Define structs and functionize request parsing.

- pkg/glusterfs/controllerserver.go
Reverts gluster/gluster-csi-driver#48
> Revert "Define structs and functionize request parsing."

- examples/kubernetes/csi-deployment.yaml
This PR adds the missing deployment artifacts which are missed in #28
> updated deployment artifacts in csi-deployment file

- pkg/glusterfs/controllerserver.go
- pkg/glusterfs/driver.go
- pkg/glusterfs/identityserver.go
- pkg/glusterfs/nodeserver.go
Fixes #https://github.com/gluster/gluster-csi-driver/issues/55
> Fix golint failures in controller,driver and identityserver.

- pkg/glusterfs/controllerserver.go
This PR functionize parsing request and fill data on subjected structs. The plan is to use these structs for storing gd2 specific values and also CSI driver specific values across the source or servers.
> Define structs and functionize request parsing

- README.md
Adds the go-report to Readme file
> added go-report card link to Readme file

- examples/kubernetes/csi-deployment.yaml
- pkg/glusterfs/controllerserver.go
- pkg/glusterfs/utils/config.go
This merges a few minor things I've updated in my experimentation. I think these would be generally useful apart from the work I've been doing.
> Minor fixes

- scripts/mdl-style.rb
> Add markdown rules url for reference.

- docs/releases.md
This list down details about CSI driver release process.
> Add releases.md.

- examples/kubernetes/csi-deployment.yaml
Fixes driver not found issue in if kubernetes 1.12 deployment
> Fix driver not found error in kubernetes 1.12

- pkg/glusterfs/controllerserver.go
- pkg/glusterfs/driver.go
- pkg/glusterfs/identityserver.go
- pkg/glusterfs/nodeserver.go
> Some error message cleanup

- CHANGELOG.md
- pkg/glusterfs/driver.go
> Update driver version & changelog to 0.0.9

- README.md
With the latest k8s, we dont need to enable some of the mentioned feature gates by command line.
> Remove supported flags from feature gate description.

- pkg/glusterfs/controllerserver.go
>     Add support for replica 3 volumes via SC param.

- README.md
> Correct the documentation about snapshot.

- Gopkg.lock
- Gopkg.toml
- examples/kubernetes/csi-deployment.yaml
- pkg/glusterfs/controllerserver.go
- pkg/glusterfs/identityserver.go
- pkg/glusterfs/nodeserver.go
This patch updates the `gluster-csi-driver` for CSI v1.0.0
> support for CSI v1.0.0

- Gopkg.lock
- Gopkg.toml
- scripts/install-reqs.sh
> Update Kube dependency to v1.13.0

- Gopkg.lock
- Gopkg.toml
- README.md
- examples/kubernetes/csi-deployment.yaml
- examples/kubernetes/driver-registry-crd.yaml
- examples/kubernetes/node-info-crd.yaml
- pkg/glusterfs/controllerserver.go
- pkg/glusterfs/identityserver.go
- pkg/glusterfs/nodeserver.go
This PR revert back the changes made for CSI v1.0.0
> Revert back changes made for CSI v1.0.0

- pkg/glusterfs/controllerserver.go
as per CSI spec if the operation is already in progress
CSI driver needs to return the aborted error code
Fixes: #108
> Return aborted error code if operation is already in progress

- README.md
- examples/kubernetes/pvc.yaml
- examples/kubernetes/storage-class.yaml
> Graduate beta annotations to GA in examples and readme.

- pkg/glusterfs/controllerserver.go
> Fix go cyclo issues in code.

- README.md
Signed-off-by: hchiramm <hchiramm@redhat.com>
> Update Deployment README with GCS deployment method.

- Gopkg.lock
- Gopkg.toml
- README.md
- examples/kubernetes/csi-deployment.yaml
- pkg/glusterfs/controllerserver.go
- pkg/glusterfs/identityserver.go
- pkg/glusterfs/nodeserver.go
Tested logs are provided in https://github.com/gluster/gcs/pull/77
> Add support for CSI v1.0.0

- pkg/glusterfs/controllerserver.go
- pkg/glusterfs/driver.go
- pkg/glusterfs/identityserver.go
- pkg/glusterfs/nodeserver.go
- pkg/glusterfs/utils/config.go
minReplicaCount and maxReplicaCount
are global variable no need to pass
them as function arguments.
> Remove redundant function parameters

- examples/kubernetes/csi-deployment.yaml
Remove deprecated driver-registrar
Add cluster-driver-registrar and node-driver-registrar
Fixes: #139
> update  sidecar containers to latest stable version

- pkg/glusterfs/Dockerfile
> Update Golang version to 1.11 from 1.10

- CHANGELOG.md
- pkg/glusterfs/driver.go
Update gluster-csi-driver version to 1.0.0
> Update gluster-csi-driver version to 1.0.0

- pkg/glusterfs/Dockerfile
> Update centos version to 7.6.1810 tag

- Gopkg.lock
- Gopkg.toml
- pkg/glusterfs/controllerserver.go
- pkg/glusterfs/nodeserver.go
This PR avoid the logging of secrets 
> Avoid logging secret

- README.md
- examples/kubernetes/thin-arbiter-pod.yaml
- examples/kubernetes/thin-arbiter-pvc.yaml
- examples/kubernetes/thin-arbiter-storageclass.yaml
- pkg/glusterfs/controllerserver.go
This PR adds the thin arbiter support in gluster-csi-driver
tested and works fine as expected
------
Fixes #151
> Add thin arbiter  support

- extras/centos-ci.sh
> Fix build in centos

- pkg/glusterfs/controllerserver.go
> Fix gocyclo issue

- pkg/gluster-virtblock/Dockerfile
- pkg/glusterfs/Dockerfile
This moves the final image of the containers to centos:7 and adds a `yum
update` to the container build process in order to make sure we
incorporate the latest security fixes.
no
> Run yum update in final container

- pkg/gluster-virtblock/Dockerfile
- pkg/glusterfs/Dockerfile
update dockerfile to use the nightly gluster release6 repo
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
> update dockerfile to use nightly gluster release6 repo
